### ISSUE TITLE
Add data to tutorials

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/unfold#1]
We need to ask for permission to also publish the data for the tutorials.

**Comment by behinger** [comment]
@olafdimigen did you prepare participant 11 for the cutingEEG workshop? Then we could update the tutorial 4 and upload the reduced dataset.

**Comment by olafdimigen** [comment]
@behinger --> answered this in other repo

**Comment by behinger** [comment]
the data are now finally in the tutorial ;) http://osf.io/wbz7x/
