### ISSUE TITLE
uf_erpimage split_by 'cond' doesn't work with "alignto"

### ISSUE THREAD

**Issue by MartynaPlomecka** [unfoldtoolbox/unfold#106]
Hi, 
I noticed that splitting up the uf_erpimage plot based on the condition is not compatible with the 'alignto' argument.
Could you take a look at the problem?
Thanks!

**Comment by behinger** [comment]
Thanks for reporting!
I know what it is and how to fix it but I haven't had the time yet. One just needs to subselect EEG.urevent the same way that one subselects EEGout.data

**Comment by behinger** [comment]
I couldnt replicate this problem (anymore?). Plain alignto + split_by works for me

![grafik](https://user-images.githubusercontent.com/10183650/124283523-49f93b80-db4c-11eb-99bc-e35737e4b1b3.png)

Closing this for now - but if you remember more details happy to fix it later - maybe it wont take a year this time ;)
