### ISSUE TITLE
uf_plotParamTopo: only last topo has sensible colormap

### ISSUE THREAD

**Issue by olafdimigen** [unfoldtoolbox/unfold#110]
Under Matlab 2021a (windows), **only the last topography in the topo series is assigned a colormap**, the other topographies have the correct contour lines, but only display some uniform color across the entire head (in my case turquoise, which does not even seem to be in the colormap). (More precisely, the colormap of preceding topographies is replaced by the uniform colormap for reasons I have not looked into).

**Comment by olafdimigen** [comment]
The same issue of course also affects plot_topobutter (which is called by uf_plotParam).

**Comment by behinger** [comment]
fixed through fcf1f86 - I just had to update to newest eegvis version which I forgot to do.. #
