### ISSUE TITLE
uf_epoch gave error for input argument of type 'string'

### ISSUE THREAD

**Issue by ufangYang** [unfoldtoolbox/unfold#115]
it is possible to replace the " in the functions with ' so that users who have < Matlab2018 won't encounter this issue? thanks a bunch!

**Comment by behinger** [comment]
thanks for reporting! This should be fixed in 082d429 :-)

**Comment by ufangYang** [comment]
thank you!

**Comment by olafdimigen** [comment]
fixed (again?) in a8c7ed1
