### ISSUE TITLE
First R^2-value of n-fold cross-validation incorrect

### ISSUE THREAD

**Issue by olafdimigen** [unfoldtoolbox/unfold#117]
Computation of cross-validated r2, tested with 3 folds (i.e., 2 fold events), spaced at 1/3 and 2/3 of cont. data.
Function returns 3 values, but first one is negative:

`R2 = uf_checkmodelfit(EEG,'method','crossValR2','fold_event',{'foldmarker'},'channel',1)`

Resulting in the following R2:   `[-0.583    0.1999    0.2045] % note negative value in R1(1)`

**Comment by behinger** [comment]
while R² can never be <0, cross-validated R² can be. This was very unintuitive for me.
So it is possible, but seems unlikely with your other two values.

Could you add more folds (randomly placed, just for testing) to further debug it?

**Comment by olafdimigen** [comment]
Good point, thanks. Looked at it further and this was indeed a consequence of very unevenly spaced fold events in my testing data. Closing this issue.
