### ISSUE TITLE
Error using uf_timeexpandDesignmat() with formulae of different complexity

### ISSUE THREAD

**Issue by ibrilma** [unfoldtoolbox/unfold#123]
I don't know if that is really an issue, but whenever I try to model several events with different formulae, the order of the events in the cfg structure needs to follow the complexity of the models for these event from less to more complex. Following works:

cfgDesign.formula = {'y ~ 1','y ~ 1+cat(ref)+Dim_1+Dim_2'};
EEG = uf_timeexpand...(EEG);

Following formula does not:

cfgDesign.formula = {'y ~ 1+cat(ref)+Dim_1+Dim_2', 'y ~ 1'};

The error message is:

Error using horzcat
Dimensions of arrays being concatenated are not consistent.

Error in uf_designmat>combine_deconvsets (line 659)
    samenameext = ismember(currnameext,[setA{:}]);

Error in uf_designmat (line 165)
                deconvAll = combine_deconvsets(deconvAll,EEG2,k);
 
Is this intended? Is there a solution?

**Comment by olafdimigen** [comment]
Before looking into this more deeply, I can say that this is clearly not a general issue, the less complex formula (here `y~1`) can come first or last. I assume that you made sure that the arguments in `cfgDesign.eventtypes` were ordered correspondingly (same order) to the entries in your `cfgDesign.formula`?

**Comment by olafdimigen** [comment]
@ibrilma Any follow-up on this? Did checking the formula order solve the problem?

**Comment by ibrilma** [comment]
Hi Olaf, sorry that I didn't get back to you. No, this does not cause the error. I checked that more than once. I'll inform you when I find something.BestIngmar--Dr. Ingmar Brilmayer"Communication Electrified"Department of German Language and Literature IUniversity of CologneAlbertus Magnus Platz50923 Cologne, Germanyphone: +49(0)221 470 89910
-------- Ursprüngliche Nachricht --------Von: Olaf Dimigen ***@***.***> Datum: 11.09.21  12:43  (GMT+01:00) An: unfoldtoolbox/unfold ***@***.***> Cc: ibrilma ***@***.***>, Mention ***@***.***> Betreff: Re: [unfoldtoolbox/unfold] Error using uf_timeexpandDesignmat() with
  formulae of different complexity (#123) 
@ibrilma Any follow-up on this? Did checking the formula order solve the problem?

**Comment by olafdimigen** [comment]
@ibrilma Ok - if you upload or email a reproducible example (code snippet and some data), we'd be happy to look into the issue
