### ISSUE TITLE
uf_designmat() stalls under Mac if spline-predictor in model

### ISSUE THREAD

**Issue by olafdimigen** [unfoldtoolbox/unfold#45]
-- Small model containing single spline predictor [ y ~ 1 + spl(xxx,6) ]
-- Same model with linear predictor [y ~ 1 + xx] runs smoothly on same computers
-- Reproduced on two Macbooks
  -- Mac OS 10.13.4 (8 GB RAM, 2.7 GHz)
  -- Running Matlab 2015b for Mac

Will try to get a Mac test-system, but have none. Seems critical.

**Comment by behinger** [comment]
It freezes or it stops?
What about others fitting methods?

Can you run the unittests? Especially the test_splines

**Comment by olafdimigen** [comment]
Froze, no error message. I could not test on those systems, could not run unit tests either. But aborting script execution (CTRL-C) produces the following error output, indicating (but only indicating) that the script froze/stalled in one these lines:

In quantile (line 54)
    q = quantile(data,varargin{:});

In uf_designmat_spline (line 136)
                spl.knots =  quantile(spl.paramValues,linspace(0,1,spl.nSplines));

In uf_designmat (line 565)
            [EEG, ~,nanlist] =
            uf_designmat_spline(EEG,'name',cfg.spline{s}{1},'nsplines',cfg.spline{s}{2}(1),'paramValues',t{:,cfg.spline{s}{1}},'splinespacing',cfg.splinespacing,'splinefunction',cfg.spline{s}{3},'cyclical_bounds',bounds);

In uf_designmat (line 150)
            EEG2 = uf_designmat(EEG,cfgSingle);

I'll get a Mac for proper testing in the next days.

**Comment by behinger** [comment]
OK. Preliminary solution is to turn of preconditioning.quantile is a Default Matlab function!

Am 25. Juni 2018 18:44:20 MESZ schrieb Olaf Dimigen <notifications@github.com>:

**Comment by behinger** [comment]
Ah sorry.its already in the Generation of the designmat.ok No idea

Am 25. Juni 2018 18:44:20 MESZ schrieb Olaf Dimigen <notifications@github.com>:

**Comment by olafdimigen** [comment]
Tested now - could not reproduce this issue under Mac OS ("Sierra") runnning Matlab R2018a. 
Let's see whether similar reports come in.

**Comment by behinger** [comment]
Did you test on the same dataset?
Did you run the unittest on the problematic computer? Maybe we have an inputdata Problem.

Am 27. Juni 2018 15:56:32 MESZ schrieb Olaf Dimigen <notifications@github.com>:

**Comment by behinger** [comment]
Is there any news? Else I will close this issue
