### ISSUE TITLE
plot_butterfly without timewindow

### ISSUE THREAD

**Issue by anligert** [unfoldtoolbox/unfold#55]
If I don't specify a time window for my plot_topobutter, plot_butterfly has an empty plt.timeidx.
l.19 
if isempty(g.time)
    plt.time = inp_times;
    plt.data = inp_data(:,:,1);
    plt.timeidx = ones(size(inp_times));
...
does not work.

**Comment by behinger** [comment]
The bug only occurs if you in addition specify p-values and is for the rectangular background.
