### ISSUE TITLE
matlab inconsistency reference/effect coding & reference group

### ISSUE THREAD

**Issue by anligert** [unfoldtoolbox/unfold#56]
Bene here:

With reference coding matlab takes the first variable as the reference group (and omits it from an explicit variable).
With effect coding, matlab takes the last one as the implicit variable.

This could actually make sense, as depending how you see it, the reference group is the first group modeled and the other predictors are the difference to that group. We should document this behaviour as it might have unpredicted consequences :)

**Comment by behinger** [comment]
This is indeed as intended. Not going to fix
