### ISSUE TITLE
uf_predictContinuous duplicates my params

### ISSUE THREAD

**Issue by anligert** [unfoldtoolbox/unfold#63]
I have a non-categorical variable containing 0 and 1. When applying uf_predictContinuous, it returns this parameter sevenfold with values of 1 each.

**Comment by anligert** [comment]
The type is ''continuous_converted''

**Comment by behinger** [comment]
This is the indendent behaviour. If you have an dummycoded predictor but do not specify it as categorical, then the toolbox assumes it is a continuous variable.

In principle we could add a check to see if there are more than two unique values, but already at effect coding there would be three unique values. I will close this as wontfix.
