### ISSUE TITLE
Include/remove cbrewer dependency

### ISSUE THREAD

**Issue by wanjam** [unfoldtoolbox/unfold#64]
Just noticed that `uf_plotDesignmat.m` & `spline-plot.m` depend on cbrewer ([this one?](https://de.mathworks.com/matlabcentral/fileexchange/34087-cbrewer-colorbrewer-schemes-for-matlab)), which is currently not part of unfold.  I suggest adding it to this repository, as I think their license would allow for that to be included in this repository.

**Comment by behinger** [comment]
Hi! I added the package. It was originally in the submodule "eegvis", but I think under unfold/lib/cbrewer makes much more sense :) Thanks a lot!
