### ISSUE TITLE
add_marginal fails due to identical name for interaction terms

### ISSUE THREAD

**Issue by olafdimigen** [unfoldtoolbox/unfold#76]
Here a minimal example for a bug encountered in uf_add_marginal. Reason for the bug is that cat * continuous interaction terms get the same predictor names in **ufresult_avg.param.name** for several different event types.

**MODEL FORMULA:**
```
cfgDesign.eventtypes  = {'Trialonset','Stimulus','Response'};
cfgDesign.formula     = {'y ~ 1', 'y ~ 1 + somecontinpredictor * cat(somecategoricalpredictor)', 'y ~ 1 + somecontinpredictor * cat(somecategoricalpredictor)'};

```    
    % where...
    % somecontinpredictor is a contin. predictor
    % somecategoricalpredictor has 3 levels
    
    % model is solved successfully
    % however, when calling
    
    results = uf_addmarginal(results);
    
    % uf_addmarginal crashes in line 164:
            
    ufresultavg_ix(end+1) = find(strcmp(pOther{1},{ufresult_avg.param.name})); 
    
    % The reason is that the assignment fails because the interaction terms for "Stimulus" and "Response" 
    have the same name in "ufresult_avg.param.name" (**):
    
    {'(Intercept)'                }
    {'2_(Intercept)'              }
    {'somecontinpredictor'             }
    {'somecategoricalpredictor_5'               }
    {'somecategoricalpredictor_6'               }
    {'somecontinpredictor:somecategoricalpredictor_5'} % **
    {'somecontinpredictor:somecategoricalpredictor_6'} % **
    {'3_(Intercept)'              }
    {'3_somecontinpredictor'           }
    {'3_somecategoricalpredictor_5'             }
    {'3_somecategoricalpredictor_6'             }
    {'somecontinpredictor:somecategoricalpredictor_5'} % **
    {'somecontinpredictor:somecategoricalpredictor_6'} % **``

**Comment by behinger** [comment]
Turns out there were two bugs, both in uf_designmat.
1. Interactions were wrongly renamed
1. Multi-level predictor interactions were added multiple times to EEG.unfold.variablenames, thus making the later renaming function fail.

Should work now

**Comment by behinger** [comment]
Commit: d6d9681fba03eed39b10ef608ddcea1a015f18ef

**Comment by behinger** [comment]
is this fixed?
