### ISSUE TITLE
Bug: uf_continuousArtifactDetect() uses critically buggy version of basicrap.m (quickfixed)

### ISSUE THREAD

**Issue by olafdimigen** [unfoldtoolbox/unfold#77]
The included version of ERPLAB's **basicrap.m** contains a critical bug due to a misplaced `break` statement. The consequence is that the detection of time windows exceeding the max-amplitude criterion is incorrect with multi-channel EEG inputs, that is, if more than one channel is checked for artifacts. `uf_continuousArtifactDetect()` uses this subfunction to detect bad intervals. The practical consequence is that if the first EEG channel is good, zero bad data intervals are detected in the other channels and bad data is entered into the deconvolution model. I have commited a quickfix to repair the curernt (outdated) version of basicrap.m. However, a quick look at https://github.com/lucklab/erplab suggest that the issue has been fixed there; need to include the most current versions of ERPLAB subfunctions.

**Comment by behinger** [comment]
any reason not to just copy over the newer function?

Maybe we should add a warning to this function. Our idea back then was to only give an example of a cleaning function, this one is pretty naive. I was also naive in thinking nobody would use it :-D
Best, Bene

**Comment by olafdimigen** [comment]
No principal reason - I had hotfixed it before I thought of looking at the recent ERPLAB version... :-)

In general, I do think we should offer some principal suggestion for continuous artifact detection (like the ERPLAB routine), since many users will not have their own routine for that purpose. Epoch-based artifact detection is still the norm and in my experience, few users do a manual screening of all raw data that would result in a suitable table with bad intervals. EEGLAB also offers no functionality for that. I will check and commit the current ERPLAB basicrap.m.

**Comment by olafdimigen** [comment]
done
