### ISSUE TITLE
Bugs in uf_addmarginal and uf_imputeMissing (if multiple event types are summarized)

### ISSUE THREAD

**Issue by olafdimigen** [unfoldtoolbox/unfold#82]
line 106 to 121 compare event combinations. If paramEvents look like this for example... 

`paramEvents = { {'stimA','stimB','stimC'} , {'respX','respY'} }`

...then strcmp() function in line 112 crashes because `strcmp` only compare cell arrays of the same length (if the length is >1), but the length differs in my example above (length 3 and 2)

```
% Comparing two cell arrays is not so easy, so we have to manually find out
% which two event combinations exist.
uniqueParamEvents = [];
for cTest = paramEvents
   is_unique_event = 1;
   for cAgainst = uniqueParamEvents
       if all(strcmp(cAgainst{1},cTest{1})) % <-- problematic strcmp
           is_unique_event = 0;
           break
       end
   end
   if is_unique_event
       uniqueParamEvents = [uniqueParamEvents cTest];
   end
       
end
```

Not offering fix cause unsure about purpose of whole comparison

**Comment by olafdimigen** [comment]
Same bug also in uf_imputeMissing, I have fixed it there (see ommit to development branch) but not in uf_addmarginal)

**Comment by olafdimigen** [comment]
Also commited a preliminary test-fix for the bug in uf_addmarginal as well, however, please check(!), since I can't quite figure out what the purpose of that loop is in the first place

**Comment by behinger** [comment]
I should have never allowed multiple event-types without them being summarized somehow to one field... maybe we can remove this complication in a future version? I.e. if multiple events are defined then just combine them with a "+" or something.

ok I fixed the bug in uf_addmarginal and took your bugfix for uf_imputeMissing. I added unittests for both bugs.

**Comment by behinger** [comment]
oh btw. there was no real purpose, I could have just look up the unique events  in ufresult.unfold.eventtypes ... which I did now remoing this whole convolute :)
