### ISSUE TITLE
uf_predictContinuous: placement of "quantile" evaluation points

### ISSUE THREAD

**Issue by olafdimigen** [unfoldtoolbox/unfold#85]
I really don't like that the first and last point at which a predictor/spline is evaluated is at the 0th and 100th percentile of the distribution if you go for cfg.automethod = 'quantile' set an cfg.auto_n.

If the predictor is not uniformly but normally distributed, the resulting estimates will be extremely noise at those percentiles (0%, 100%). Will propose a solution.

**Comment by behinger** [comment]
I agree,
for the "linear" case, I had solved that problem as follows:
```           
contmax = max(predVal);
contmin = min(predVal);
ran = contmax-contmin;
warning('moving min/max inside by 0.05 of total range in order to reduce bad extreme-estimates');
 contValueSelect = linspace(contmin+0.05*ran,contmax-0.05*ran,cfg.auto_n);
```
I put the warning there just in case somebody wonders why its not exactly the limits.

For the quantile I probably forgot, I was mostly using linear.
Would that work?
We should probably give an option though to get the fullrange. Maybe "fullrange", "true" ? not very good name yet.

**Comment by olafdimigen** [comment]
I don't think the first point should be placed at a hard-coded 5% / 95% either. Maybe we should not call the auto_n input "quantile" but simply "bins". Then, for example, if the user asks for 4 bins, I would probably place them at: 20%, 40%, 60%, 80%. In other words, I would do this:

`contValueSelect = linspace( 1/(cfg.auto_n+1), 1-1/(cfg.auto_n+1), cfg.auto_n)`

Of course, the risk of this is that one ignores interesting things that may happen at the extremes of the distribution (in the spline case). But the evaluated values should be much more stable that at the extremes for predictors with a Gaussian/non-uniform distribution.

**Comment by behinger** [comment]
Sounds very reasonable to me.

Do you pull this in to the development branch or should I?
We then merge it to unfold 1.1 once the JoV article is out
