### ISSUE TITLE
Use "eeglab redraw" to initialize EEGLAB in "init_unfold.m"

### ISSUE THREAD

**Issue by yhz-1995** [unfoldtoolbox/unfold#89]
Hello,

I suggest using "eeglab redraw" instead of "eeglab" to initialize EEGLAB toolbox in "init_unfold.m" (line 21). This will prevent clearing existing EEG data loaded in memory.

Thanks.

**Comment by olafdimigen** [comment]
Excellent suggestion, thanks. This has now been changed (both branches).

**Comment by behinger** [comment]
This commit: 939ee1c97f81739780b3002f3d5186826168805a
