### ISSUE TITLE
uf_addmarginal implement AME not only MEM

### ISSUE THREAD

**Issue by behinger** [unfoldtoolbox/unfold#91]
I just made it more clear what marginal we are adding:
```
% Note: This calculates the marginal effect at mean (MEM), that is f(E(x)). In other
% words, it calculates the effect at the average of the continuous covariate. An 
% alternative would be to calculate the average marginal mean (AME) E(f(x)). In 
% other word, the average effect of the predictor over all continuous
% covariate values. The latter is not implemented.
```
We should implement AME; it makes much more sense for circular predictors

Thanks to 周云晖 (Yunhui Zhou) for notifying me!

**Comment by yhz-1995** [comment]
I have created a pull request for this (#92). Please check if my implementation is correct or not.

**Comment by behinger** [comment]
jup! Saw it. Looks good so far. I am reviewing it right now, but not sure if I will complete it today.

I'm also writing a unittest for it.

**Comment by behinger** [comment]
Unittests are in release1.1 branch: 

531cb45f45be95d0a586681dc0a721df4415d96e

**Comment by yhz-1995** [comment]
I see the updated function in master branch. Thanks for your work. One minor suggestion: the default option of `cfg.type` in `uf_addmarginal.m` (line 60) should be the same as the comments in this function (line 26).

**Comment by behinger** [comment]
Thanks for your help. I fixed the typo!
