### ISSUE TITLE
Bug: Incorrect data representation of 2 x 3 interactions (EEG.unfold.variabletypes)

### ISSUE THREAD

**Issue by olafdimigen** [unfoldtoolbox/unfold#97]
Summary: 
When creating the EEG.unfold structure, `uf_designmat() `seems to misrepresent interactions where one factor has > 2 levels, leading to an error in the case that there is also a spline predictor in the formula (and possibly to other mayhem if there is not)

Description:
X is a factor with 3 levels
B is a factor with 2 levels

Let the formula be:
` formula: {'y ~ 1 + cat(X) * cat(B)'}`

...then uf_designmat.m creates the following data structure:

```
> formula: {'y ~ 1 + cat(X) * cat(B)'}
> X: [6197×6 double]
> variabletypes: {'intercept'  'categorical'  'categorical'  'interaction'  **'interaction'**}
> variablenames: {'(Intercept)'  'B'  'X'  'B:X'}
> colnames: {1×6 cell}
> cols2variablenames: [1 2 3 3 4 4]
> cols2eventtypes: [1 1 1 1 1 1]
> eventtypes: {{1×1 cell}}
> splines: []
> codingschema: 'reference'
```
with `EEG.unfold.colnames` looking (correctly) like this:
`
>     {'(Intercept)'}    {'B_2'}    {'X_2'}    {'X_3'}    {'B_2:X_2'}   {'B_2:X_3'}`

Note the mismatch in the number of entries between variabletypes (5) and variablesnames (4) due to the double "interaction" in variabletypes. This extra entry and resulting mismatch in length of variabletypes and variablenames will produce an error further down in `uf_designmat() `if a spline predictor is part of formula

**Comment by behinger** [comment]
Thanks!
Should be fixed now. This got introduced when we fixed #76. Unfortunately I checked that only for cat(X)*continuousA and not cat(X)*cat(Y).
It was a straight forward bug, so I think it should be correct now (and added a unittest)
